import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../layout/header";
import "./globals.css";
import Footer from "../layout/footer";
import {cn} from "../ui/utils.ts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Les mains vertes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
          <body className={cn(inter.className, "bg-primary-white p-[10px] flex flex-col gap-[10px]")}>
              <Header/>
                  {children}
              <Footer/>
          </body>
      </html>
  );
}
