import {Metadata} from "next";

export const metadata: Metadata = {
    title: "Les mains vertes",
    description: "Generated by create next app",
};

export default async function Page() {

    return (
        <main>
            Page
        </main>
    );
}